# Copyright © 2025 CCP ehf.

find_package(GTest CONFIG REQUIRED)
add_executable(CcpCoreTest
    CcpCallstack.cpp
    CcpCoreTest.cpp
    CcpCrash.cpp
    CcpHash.cpp
    CcpFileUtils.cpp
    CcpMemory.cpp
    CcpMemoryTracker.cpp
    CcpSecureCrt.cpp
    CcpStatistics.cpp
    CcpThread.cpp
    CcpTime.cpp
    StringConversions.cpp
    TempFile.cpp
    CcpLog.cpp
)
target_link_libraries(CcpCoreTest PRIVATE CcpCore GTest::gtest GTest::gtest_main)

if(WITH_TELEMETRY)
    find_package(lz4 CONFIG REQUIRED)
    target_sources(CcpCoreTest PRIVATE
        CcpTelemetry.cpp
        TracyTestClient.cpp
    )
    target_link_libraries(CcpCoreTest PRIVATE lz4::lz4 Tracy::TracyClient)
endif()
if(WIN32)
    target_link_libraries(CcpCoreTest PRIVATE ws2_32)
endif()
if(APPLE)
    target_link_libraries(CcpCoreTest PRIVATE "-framework CoreFoundation")
endif()

if(CMAKE_IMPORT_LIBRARY_SUFFIX)
    add_custom_command(TARGET CcpCoreTest POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_RUNTIME_DLLS:CcpCoreTest> $<TARGET_FILE_DIR:CcpCoreTest>
            COMMAND_EXPAND_LISTS
            VERBATIM
    )
endif()

include(GoogleTest)

set_target_properties(CcpCoreTest PROPERTIES FOLDER "Tests")
# Test discovery needs to be delayed to PRE_TEST (https://gitlab.kitware.com/cmake/cmake/-/issues/21845)
gtest_discover_tests(CcpCoreTest DISCOVERY_MODE PRE_TEST)
